services:
  - type: web
    name: edinitsa-p2p
    env: node
    buildCommand: npm install
    startCommand: node server-render.js
    plan: free
    region: frankfurt
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
